### ISSUE TITLE
URL is not being rewritten

### ISSUE THREAD

**Issue by benmccann** [sormy/rollup-plugin-smart-asset#13]
Hi, thanks for providing this plugin! This is the #1 thing I most missed from Webpack! I'm having trouble figuring out how to set it up though and am not sure if there's a bug or I'm just using it wrong

I originally setup the url plugin and have things working with it:
https://github.com/benmccann/sapper-template-rollup/tree/image

Then I found this plugin and tried to switch to it:
https://github.com/benmccann/sapper-template-rollup/tree/smart-asset

You can run the project with `npm install` and then `npm run dev`. When I do that, I see a broken link where the main image is and when I do view-source I see:
```
<img alt="Success Kid" src="/client/successkid.jpg" class="svelte-1kk9opm">
```

The funny thing though is that it did inline the favicon, which is the other image on the page, so it's partially working

Is there anything I might be doing wrong?

**Comment by benmccann** [comment]
@sormy I was wondering if you might have a chance to look at this? Thanks again for the great plugin. I'm really excited to use it if I can figure out this bug

**Comment by sormy** [comment]
I apologize for slow response.

Asset `successkid.jpg` is 79kb. The image exceeds 14kb default limit and plugin falls back to copy.

This is outlined in README: https://github.com/sormy/rollup-plugin-smart-asset#mode-inline

Configuration below inlines all assets <1000kb:

```js
			smartAsset({
				url: 'inline',
				maxSize: 1000,
			}),
```

There is no issue with the plugin.
