### ISSUE TITLE
Maintain folder structure for files?

### ISSUE THREAD

**Issue by recs182** [sormy/rollup-plugin-smart-asset#16]
I would like to maintain folder structure for files but could not found a way to do this in the options.
If you could enlighten me about a existent way of doing or a plan to add support to such feature.

Thanks in advance. Very good plugin, I must say.

**Comment by sormy** [comment]
You can maintain files in sources as you want. Do you mean to maintain in output?

**Comment by recs182** [comment]
Yes, maintain in output, sorry if it wasn`t understandable.

**Comment by sormy** [comment]
There is no option to achieve that currently, but you can use multiple instances with different output options and different `include`/`exclude` filters.

**Comment by recs182** [comment]
Just for organization but it's ok that it can't be archive right now.

I appreciate you took the time to answer. Thanks.
