### ISSUE TITLE
How to get the asset content?

### ISSUE THREAD

**Issue by lcysgsg** [sormy/rollup-plugin-smart-asset#17]
I try to run examples, but get the error: `ReferenceError: stub is not defined`.
```js
// examples/keep-imports-cjs/dist/index.js
var imageSrc = _interopDefault(require('./image.txt'));
```

If `keep-imports` is `false`, only get the asset url. How to get the content? is `fs.readFile` right?

what's the correct way to use?

**Comment by sormy** [comment]
`keep-imports` is designed for libraries to keep `import ...` or `require(...)` as it is. It could be useful to delegate asset bundling procedure to another toolchain (web pack, rollup etc).

For applications we need to actually replace `import ...` or `require(...)` with either URL or with base64 URL. Please take a look on README and pick the mode you are looking for.

Please share your rollup config and project directory structure if you still did not get it working.

**Comment by lcysgsg** [comment]
Yeah, I have known how the `keep-imports`  works. `rollup-plugin-smart-asset` can resolve assets reference. But if it is extension name is `.txt`, `import ...` or `require` can not work.

How to run this [example](https://github.com/sormy/rollup-plugin-smart-asset/blob/master/examples/keep-imports-cjs/dist/index.js)?
`$ node ./index.js` will get the error. The `image.txt` content executed as a program.
![image](https://user-images.githubusercontent.com/19550000/103333389-cbdab000-4aa8-11eb-81de-811fd0b8e1eb.png)

If there is a `image.txt` and `keep-imports` is `true`. The `import ...` or `require` can not work.
If there is a `image.txt` and `keep-imports` is `false`. Will get assets path, should I use `fs.readFile` or [rollup-plugin-string](https://www.npmjs.com/package/rollup-plugin-string) to get the content? 

My problem is how to get a file content, as above example get the `image.txt` content `stub`.

i am a newer, thank you answer.

**Comment by sormy** [comment]
Unfortunately, this plugin doesn't have an option to read contents at this time. It imports all assets as URL: url to asset or to base64 data URL if asset is inlined.

You can use `fs.readFile()` or/and `fs.readFileSync()` instead of `require()` or `import ...` to read any file.

**Comment by lcysgsg** [comment]
OK, I understand, thanks a lot!
