### ISSUE TITLE
Absolute path imports to assets don't work - "(!) Plugin smart-asset: Unable to copy asset"

### ISSUE THREAD

**Issue by fabis94** [sormy/rollup-plugin-smart-asset#18]
Version: rollup-plugin-smart-asset@2.1.0

There's a line of code in the source code that seems to break the path to the asset which in turn prevents this plugin from being able to copy the asset to the build directory:

https://github.com/sormy/rollup-plugin-smart-asset/blob/6c6d1ea97f81ef4d8b67216d1376920ed1f1277c/src/smartAsset.js#L185

I think this happens because i'm using `@rollup/plugin-alias` to convert all imports to absolute paths (e.g. `@src/x/y` =>  `/home/user/code/rollup-project/src/x/y`) and this plugin doesn't support absolute imports.

The reason this happens is because `source` is something like `/home/user/code/rollup-project/src/assets/image.png` and `importer` is something like `/home/user/code/rollup-project/src/components/widget.js`, so `join(dirname(importer), source)` invoked on those variables ends up returning `/home/user/code/rollup-project/src/components/home/user/code/rollup-project/src/assets/image.png` which is of course completely off.

It would be great if this could be fixed and absolute path import support would be introduced, because using absolute (aliased) paths is a better practice anyway.

**Comment by fabis94** [comment]
This fix seemed to work: https://github.com/sormy/rollup-plugin-smart-asset/pull/19

**Comment by sormy** [comment]
Thanks for contribution. The new version with the fix has been published v2.2.1. Resolving.
