### ISSUE TITLE
Not compatible with CommonJS plugin?

### ISSUE THREAD

**Issue by yfwz100** [sormy/rollup-plugin-smart-asset#22]
The plugin is not possible to handle something like `./object-create.svg?commonjs-external` generated from commonjs plugin.

**Comment by sormy** [comment]
You will need to provide more details. I'm not sure if understand what the issue is.

**Comment by yfwz100** [comment]
Sorry, I really appreciate your plugin. I'll put some details here: 

When using this plugin with [commonjs](https://www.npmjs.com/package/@rollup/plugin-commonjs) plugin, the smart asset plugin will not work. I dig into the code and found that the commonjs plugin will generate names with suffix of `?commonjs-external` but smart asset plugin will not handle this type of file names (`path.extname("something.svg?commonjs-external") == ".svg?commonjs-external"`. 

I am new to rollup and don't understand the mechanism that whether this is by design.

**Comment by sormy** [comment]
Please publish a repo with the reproduction of the issue.

**Comment by yfwz100** [comment]
see https://gist.github.com/yfwz100/20229edfaf041b36a188dcbb79dcc315

**Comment by sormy** [comment]
I can confirm it doesn't work with commonjs wrappers at this time.

**Comment by sormy** [comment]
I have a fix, will release new version soon.

**Comment by yfwz100** [comment]
Thanks for reply. I've converted my `require`s to ES `import`s to avoid using commonjs plugin. 

However, inline `require` is more convenient than putting `import`s at the first of the file.

**Comment by sormy** [comment]
The fix is released with v2.1.2. Please confirm if it works well.

**Comment by yfwz100** [comment]
It works now. Thanks!
