### ISSUE TITLE
include/exclude option

### ISSUE THREAD

**Issue by pantoninho** [sormy/rollup-plugin-smart-asset#6]
This plugin works great and it really makes a difference on my project! Thanks!

It would be very helpful if we could match files per path (instead of just per extension) using the conventional include/exclude option on the plugin configuration.

Is it something you could consider?

**Comment by sormy** [comment]
Added in `2.0.3` version, please take a look.

**Comment by pantoninho** [comment]
I'm sorry, I was not in the latest version. Works as expected -- going to close this issue. Thanks!
