### ISSUE TITLE
multi-output builds

### ISSUE THREAD

**Issue by pantoninho** [sormy/rollup-plugin-smart-asset#7]
Given a multi-output configuration with `copy` mode:
```
output: [
            { dir: 'dist/cjs', format: 'cjs', sourcemap: 'inline' },
            { dir: 'dist/esm', format: 'es', sourcemap: 'inline' }
        ]
```
```
 smartAsset({
                url: 'copy',
                keepImport: true
            }),
```

`smart-assets` only exports the assets to the first output directory (which in this case is `dist/cjs`)

**Comment by sormy** [comment]
confirmed

**Comment by sormy** [comment]
Fixed in `2.0.5`.

**Comment by sormy** [comment]
Hi, could you please quickly check if new version resolves the issue. Thank you.

**Comment by pantoninho** [comment]
Hello! I'm sorry for commenting back so late.
I can confirm `2.0.5` has solved my issue.

Thank you very much for your great work.
