### ISSUE TITLE
absolute publicPath gets corrupted

### ISSUE THREAD

**Issue by ghost23** [sormy/rollup-plugin-smart-asset#8]
Hi,

I have this configuration:

```
smartAsset({
   url: "copy",
   publicPath: "http://localhost:4004/assets",
   assetsPath: "assets/"
})
```

And in my code I have this:

```
import photo from './icon-square-small.png';

...

// in a react tree
<img src={photo} />
```

If I build this with rollup, in the resulting javascript file I see:

```
/* loaded by smart-asset */
var photo = "http:/localhost:4004/assets/icon-square-small.png";
```

As you can see, now it is: `http:/local....`, so one slash is missing now.

Do I have to configure it differently, or is this a bug?

Thank you.

**Comment by sormy** [comment]
It is a regression bug. Thanks for reporting. You could try one of previous versions until i will release new version

**Comment by sormy** [comment]
Fixed in 2.0.6. Let me know if it works well.

**Comment by ghost23** [comment]
Perfect 👍 Will test on Monday. Thanks already for the quick reply.

**Comment by sormy** [comment]
ping

**Comment by ghost23** [comment]
Upps, I'm sorry. I tested today and it works perfectly. Thank you very much for the quick responses.
